version: '3' 
services:
  rest-dev-vnc-docker:
    image: openkbs/rest-dev-vnc-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest-dev-vnc-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    #env_file:
    #  - ./.env
    ports:
      - 5901:5901
      - 6901:6901
    volumes:
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace
      - ./Projects:/home/developer/Projects
      - ./.eclipse:/home/developer/.eclipse
      - ./eclipse-workspacee:/home/developer/eclipse-workspace
